/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DesignerPageRouteImport } from './routes/designer-page'
import { Route as GameInfoFormRouteImport } from './routes/game-info-form'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminGamesRouteImport } from './routes/admin/games'
import { Route as AdminGenresRouteImport } from './routes/admin/genres'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator/analytics'
import { Route as CreatorMyGamesRouteImport } from './routes/creator/my-games'
import { Route as CreatorOverviewRouteImport } from './routes/creator/overview'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin/submissions/index'
import { Route as AdminSubmissionsSubmissionIdRouteImport } from './routes/admin/submissions/$submissionId'
import { Route as StoreGamesSlugRouteImport } from './routes/store.games.$slug'
import { Route as CreatorGamesGameIdEditRouteImport } from './routes/creator/games.$gameId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerPageRoute = DesignerPageRouteImport.update({
  id: '/designer-page',
  path: '/designer-page',
  getParentRoute: () => rootRouteImport,
} as any)
const GameInfoFormRoute = GameInfoFormRouteImport.update({
  id: '/game-info-form',
  path: '/game-info-form',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorMyGamesRoute = CreatorMyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorOverviewRoute = CreatorOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsSubmissionIdRoute =
  AdminSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AdminRoute,
  } as any)
const StoreGamesSlugRoute = StoreGamesSlugRouteImport.update({
  id: '/store/games/$slug',
  path: '/store/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorGamesGameIdEditRoute = CreatorGamesGameIdEditRouteImport.update({
  id: '/games/$gameId/edit',
  path: '/games/$gameId/edit',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/creator': typeof CreatorRouteWithChildren
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/my-games': typeof CreatorMyGamesRoute
  '/creator/overview': typeof CreatorOverviewRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/creator/games/$gameId/edit': typeof CreatorGamesGameIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/my-games': typeof CreatorMyGamesRoute
  '/creator/overview': typeof CreatorOverviewRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
  '/creator/games/$gameId/edit': typeof CreatorGamesGameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/creator': typeof CreatorRouteWithChildren
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/my-games': typeof CreatorMyGamesRoute
  '/creator/overview': typeof CreatorOverviewRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/creator/games/$gameId/edit': typeof CreatorGamesGameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/creator'
    | '/designer-page'
    | '/game-info-form'
    | '/library'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/audit-log'
    | '/admin/games'
    | '/admin/genres'
    | '/admin/transactions'
    | '/admin/users'
    | '/creator/analytics'
    | '/creator/my-games'
    | '/creator/overview'
    | '/admin/'
    | '/creator/'
    | '/admin/submissions/$submissionId'
    | '/store/games/$slug'
    | '/admin/submissions/'
    | '/creator/games/$gameId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/designer-page'
    | '/game-info-form'
    | '/library'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/audit-log'
    | '/admin/games'
    | '/admin/genres'
    | '/admin/transactions'
    | '/admin/users'
    | '/creator/analytics'
    | '/creator/my-games'
    | '/creator/overview'
    | '/admin'
    | '/creator'
    | '/admin/submissions/$submissionId'
    | '/store/games/$slug'
    | '/admin/submissions'
    | '/creator/games/$gameId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/creator'
    | '/designer-page'
    | '/game-info-form'
    | '/library'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/audit-log'
    | '/admin/games'
    | '/admin/genres'
    | '/admin/transactions'
    | '/admin/users'
    | '/creator/analytics'
    | '/creator/my-games'
    | '/creator/overview'
    | '/admin/'
    | '/creator/'
    | '/admin/submissions/$submissionId'
    | '/store/games/$slug'
    | '/admin/submissions/'
    | '/creator/games/$gameId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  DesignerPageRoute: typeof DesignerPageRoute
  GameInfoFormRoute: typeof GameInfoFormRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StoreGamesSlugRoute: typeof StoreGamesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-page': {
      id: '/designer-page'
      path: '/designer-page'
      fullPath: '/designer-page'
      preLoaderRoute: typeof DesignerPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-info-form': {
      id: '/game-info-form'
      path: '/game-info-form'
      fullPath: '/game-info-form'
      preLoaderRoute: typeof GameInfoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/my-games': {
      id: '/creator/my-games'
      path: '/my-games'
      fullPath: '/creator/my-games'
      preLoaderRoute: typeof CreatorMyGamesRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/overview': {
      id: '/creator/overview'
      path: '/overview'
      fullPath: '/creator/overview'
      preLoaderRoute: typeof CreatorOverviewRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions/$submissionId': {
      id: '/admin/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/admin/submissions/$submissionId'
      preLoaderRoute: typeof AdminSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/games/$slug': {
      id: '/store/games/$slug'
      path: '/store/games/$slug'
      fullPath: '/store/games/$slug'
      preLoaderRoute: typeof StoreGamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/games/$gameId/edit': {
      id: '/creator/games/$gameId/edit'
      path: '/games/$gameId/edit'
      fullPath: '/creator/games/$gameId/edit'
      preLoaderRoute: typeof CreatorGamesGameIdEditRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGenresRoute: typeof AdminGenresRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSubmissionsSubmissionIdRoute: typeof AdminSubmissionsSubmissionIdRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminGenresRoute: AdminGenresRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSubmissionsSubmissionIdRoute: AdminSubmissionsSubmissionIdRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorRouteChildren {
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorMyGamesRoute: typeof CreatorMyGamesRoute
  CreatorOverviewRoute: typeof CreatorOverviewRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorGamesGameIdEditRoute: typeof CreatorGamesGameIdEditRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorMyGamesRoute: CreatorMyGamesRoute,
  CreatorOverviewRoute: CreatorOverviewRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorGamesGameIdEditRoute: CreatorGamesGameIdEditRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CreatorRoute: CreatorRouteWithChildren,
  DesignerPageRoute: DesignerPageRoute,
  GameInfoFormRoute: GameInfoFormRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StoreGamesSlugRoute: StoreGamesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
