/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignerPageRouteImport } from './routes/designer-page'
import { Route as GameInfoFormRouteImport } from './routes/game-info-form'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StoreGamesSlugRouteImport } from './routes/store.games.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerPageRoute = DesignerPageRouteImport.update({
  id: '/designer-page',
  path: '/designer-page',
  getParentRoute: () => rootRouteImport,
} as any)
const GameInfoFormRoute = GameInfoFormRouteImport.update({
  id: '/game-info-form',
  path: '/game-info-form',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreGamesSlugRoute = StoreGamesSlugRouteImport.update({
  id: '/store/games/$slug',
  path: '/store/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer-page': typeof DesignerPageRoute
  '/game-info-form': typeof GameInfoFormRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/store/games/$slug': typeof StoreGamesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/designer-page'
  | '/game-info-form'
  | '/checkout'
  | '/library'
  | '/login'
  | '/profile'
  | '/register'
  | '/store/games/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/designer-page'
  | '/game-info-form'
  | '/checkout'
  | '/library'
  | '/login'
  | '/profile'
  | '/register'
  | '/store/games/$slug'
  id:
  | '__root__'
  | '/'
  | '/designer-page'
  | '/game-info-form'
  | '/checkout'
  | '/library'
  | '/login'
  | '/profile'
  | '/register'
  | '/store/games/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerPageRoute: typeof DesignerPageRoute
  GameInfoFormRoute: typeof GameInfoFormRoute
  CheckoutRoute: typeof CheckoutRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StoreGamesSlugRoute: typeof StoreGamesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-page': {
      id: '/designer-page'
      path: '/designer-page'
      fullPath: '/designer-page'
      preLoaderRoute: typeof DesignerPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-info-form': {
      id: '/game-info-form'
      path: '/game-info-form'
      fullPath: '/game-info-form'
      preLoaderRoute: typeof GameInfoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/games/$slug': {
      id: '/store/games/$slug'
      path: '/store/games/$slug'
      fullPath: '/store/games/$slug'
      preLoaderRoute: typeof StoreGamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerPageRoute: DesignerPageRoute,
  GameInfoFormRoute: GameInfoFormRoute,
  CheckoutRoute: CheckoutRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StoreGamesSlugRoute: StoreGamesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
