import { FileUp, X, Upload, Check } from "lucide-react";
import { HATHOR_ORANGE, BORDER, TEXT_MUTED } from "../../types/designerTypes";
import styles from "../../DesignerPage.module.css";

export function ImportModal({
  importJsonText,
  setImportJsonText,
  importError,
  setImportError,
  onClose,
  onImport
}: {
  importJsonText: string;
  setImportJsonText: (val: string) => void;
  importError: string | null;
  setImportError: (err: string | null) => void;
  onClose: () => void;
  onImport: (text: string) => void;
}) {
  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent} style={{ maxWidth: 620, width: "90%" }}>
        <div className={styles.modalHeader}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <FileUp size={16} style={{ color: HATHOR_ORANGE }} />
            <h3 className={styles.modalTitle}>Import Page Layout JSON</h3>
          </div>
          <button onClick={() => { onClose(); setImportError(null); }} className={styles.modalCloseBtn}>
            <X size={14} />
          </button>
        </div>

        <div style={{ padding: "16px 20px", display: "flex", flexDirection: "column", gap: 14 }}>
          <p style={{ fontSize: 12, color: TEXT_MUTED, margin: 0, lineHeight: 1.5 }}>
            Upload a <code>.json</code> file or paste JSON generated by AI or exported from another session to render the page in the designer.
          </p>

          {/* Upload File Input */}
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <label
              style={{
                padding: "8px 14px", border: `1px dashed ${HATHOR_ORANGE}`, background: "rgba(242, 107, 33, 0.08)",
                color: HATHOR_ORANGE, borderRadius: 4, fontSize: 11, fontWeight: 800, cursor: "pointer",
                display: "flex", alignItems: "center", gap: 6
              }}
            >
              <Upload size={12} /> Choose .json File
              <input
                type="file"
                accept=".json,application/json"
                style={{ display: "none" }}
                onChange={e => {
                  const file = e.target.files?.[0];
                  if (file) {
                    const reader = new FileReader();
                    reader.onload = ev => {
                      const text = ev.target?.result as string;
                      if (text) {
                        setImportJsonText(text);
                        onImport(text);
                      }
                    };
                    reader.readAsText(file);
                  }
                }}
              />
            </label>
            <span style={{ fontSize: 11, color: TEXT_MUTED }}>or paste raw JSON below:</span>
          </div>

          {/* Raw Textarea Input */}
          <textarea
            value={importJsonText}
            onChange={e => { setImportJsonText(e.target.value); setImportError(null); }}
            placeholder='Paste layout JSON here... e.g. { "sections": [...] }'
            rows={12}
            style={{
              width: "100%", background: "#0c0e12", border: `1px solid ${BORDER}`, color: "#e6edf3",
              fontFamily: "monospace", fontSize: 11, padding: 12, borderRadius: 4, outline: "none",
              resize: "vertical", boxSizing: "border-box"
            }}
          />

          {importError && (
            <div style={{ padding: "8px 12px", background: "rgba(231, 76, 60, 0.12)", border: "1px solid #e74c3c", color: "#e74c3c", fontSize: 11, borderRadius: 4, fontWeight: 700 }}>
              {importError}
            </div>
          )}

          <div style={{ display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 4 }}>
            <button
              onClick={() => { onClose(); setImportError(null); }}
              style={{ padding: "8px 16px", background: "transparent", border: `1px solid ${BORDER}`, color: TEXT_MUTED, borderRadius: 4, fontSize: 11, cursor: "pointer" }}
            >
              Cancel
            </button>
            <button
              onClick={() => onImport(importJsonText)}
              style={{ padding: "8px 20px", background: HATHOR_ORANGE, border: "none", color: "#ffffff", borderRadius: 4, fontSize: 11, fontWeight: 900, cursor: "pointer", display: "flex", alignItems: "center", gap: 6 }}
            >
              <Check size={12} /> Render Page Layout
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
